topics:
  -
    name: xbox
    topic: cmd_vel
    timeout: 0.5
    priority: 100
  -
    name: ps4
    topic: cmd_vel
    timeout: 0.5
    priority: 95
locks:
  -
    name: emergency
    topic: emergency
    timeout: 0.0
    priority: 255
